---
title: "finalProject"
author: "Eric Appelbaum & Barbara Valischenko"
date: "May 22, 2019"
output: html_document
---

# Cell Phone Data

## Intro

## Libraries

```{r}
library(stringr)
library(tidyverse)
```

## Data

### Raw Data

We are using the dataset [1.4 Million Phone Reviews](https://www.kaggle.com/masaladata/14-million-cell-phone-reviews) from Kaggle. This dataset encompasses over 1.4 million reviews across various brands, models, countries, languages, and websites.

```{r}
review1 <- read.csv("data/phone_user_review_file_1.csv")
review2 <- read.csv("data/phone_user_review_file_2.csv")
review3 <- read.csv("data/phone_user_review_file_3.csv")
review4 <- read.csv("data/phone_user_review_file_4.csv")
review5 <- read.csv("data/phone_user_review_file_5.csv")
review6 <- read.csv("data/phone_user_review_file_6.csv")
```

```{r}
reviews <- rbind.fill(review1, review2, review3, review4, review5, review6)
reviews$phone_url = substring(reviews$phone_url, 13, str_length(reviews$phone_url)-1)
reviews$date = as.Date(reviews$date, "%m/%d/%Y")

reviews
```

### Alterations

```{r}
reviews_bm <- reviews %>%
  na.omit() %>%
  separate(phone_url, c("brand", "model"), sep = "-", extra = "merge")

reviews_bm
```

## EDA

```{r}
reviews_bm %>%
  na.omit() %>%
  group_by(brand, model) %>%
  summarize(count = n(), mean_score = mean(score)) %>%
  sort(mean_score)
```


```{r}

note_reviews = reviews %>%
  filter(phone_url=="samsung-galaxy-note-7") %>%
  group_by(date) %>%
  summarize(mean(score))

```

```{r}
country_reviews = reviews %>%
  filter(!is.na(score)) %>%
  group_by(country) %>%
  summarize(mean_score = mean(score))

country_reviews

country_reviews %>%
  ggplot(aes(country,mean_score)) +
  geom_bar(stat = "identity")
```

## Hypothesis Testing and ML
